---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# qNCIN

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of qNCIN like so:

``` r
# install.packages("devtools")
devtools::install_github("thereallda/qNCIN")

```

## Quick Start
### Load package

```{r}
library(tidyverse)

# if you do not have `enONE` package installed, run the following code first: 
# devtools::install_github("thereallda/enONE")
if (!requireNamespace("enONE", quietly = TRUE)) { devtools::install_github("thereallda/enONE") }
library(enONE)
library(qNCIN)
```


### Load data

```{r}
counts_df <- read.csv("data/Counts.csv", row.names = 1)
meta <- read.csv("data/metadata.csv")

# metadata for synthetic RNA
syn_id <- paste("syn",3:7, sep = "_")
syn_meta <- data.frame(
  id = syn_id,
  per = c(0.05,0.01,0.20,0,0.10)
)
```

### Filtering 

```{r}
counts_keep <- FilterLowExprGene(counts_df, 
                                 group = meta$condition,
                                 min.count = 20)
```

### Generate Factors

```{r}
# scale factor
sf1 <- calcScaleFactor(counts_keep,
                       spike.in.prefix = "FB",
                       enrich.group = meta$condition,
                      )
# adjust factor
af1 <- calcAdjustFactor(counts_keep,
                        spike.in.prefix = "FB",
                        enrich.group = meta$condition,
                        scale.factor = sf1,
                        prop.top.enrich = 1,
                        pseudo.count = 5
                        )

```

### Calculate Ratio

```{r}
qratio_df <- calcNCIN(counts_keep,
                      spike.in.prefix = "FB",
                      enrich.group = meta$condition,
                      scale.factor = sf1,
                      adjust.factor = af1,
                      filter = T,
                      pseudo.count = 5
                      )
head(qratio_df);dim(qratio_df)
```

### Synthetic RNA Calibration curve

```{r}
synScatter(ratio.df = qratio_df, syn.meta = syn_meta)
```
